spring:
  application:
    name: trade-vision-backend

  modulith:
    events:
      completion:
        mode: delete
      jdbc-schema-initialization:
        enabled: true

  flyway:
    enabled: false
    baseline-on-migration: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

logging:
  level:
    root: INFO


